<?php 
	 require_once __DIR__ . '/config/dz.php';
?>
<!DOCTYPE html>
<html lang="en">

<head>
	<title><?php echo !empty($DexignZoneSettings['pagelevel'][$CurrentPage]['title']) ? $DexignZoneSettings['pagelevel'][$CurrentPage]['title'].' | ' : '' ; echo $DexignZoneSettings['site_level']['site_title'] ?></title>
	<?php include 'elements/meta.php';?>
	<!-- FAVICONS ICON -->
	<link rel="shortcut icon" type="image/png" href="<?php echo $DexignZoneSettings['site_level']['favicon']?>">
	<?php include 'elements/page-css.php'; ?>

</head>
<body>

    <!--*******************
        Preloader start
    ********************-->
	  <?php include 'elements/preloader.php'; ?>
    <!--*******************
        Preloader end
    ********************-->

    <!--**********************************
        Main wrapper start
    ***********************************-->
    <div id="main-wrapper">

        <!--**********************************
            Nav header start
        ***********************************-->
		<?php include 'elements/nav-header.php'; ?>
        <!--**********************************
            Nav header end
        ***********************************-->
		
		<!--**********************************
            Chat box start
        ***********************************-->
		<?php include 'elements/chatbox.php'; ?>
		<!--**********************************
            Chat box End
        ***********************************-->
		
		<!--**********************************
            Header start
        ***********************************-->
        		<?php include 'elements/header.php'; ?>

                    
        <!--**********************************
            Header end ti-comment-alt
        ***********************************-->

        <!--**********************************
            Sidebar start
        ***********************************-->
		<?php include 'elements/sidebar.php'; ?>
        <!--**********************************
            Sidebar end
        ***********************************-->
		
		<!--**********************************
            Content body start
        ***********************************-->
		 <div class="content-body">
            <!-- row -->	
			<div class="container-fluid">
				<div class="row">
					<div class="col-xl-12">
						<div class="alert alert-dismissible ai-header-alert fade show mb-4">
							This is a demo of AIKit plugin made for you to test the experience of using the plugin.

							<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="btn-close">
														
							</button>
						</div>
						<p>AIKit Scheduled AI Generators allow you to schedule content to be generated by AI. Please review and edit before publishing for best results. This is not a substitute for human editing, but a drafting aid. Happy writing!</p>
						
							
						<ul class="nav nav-tabs style-1 mb-4" id="pills-tab" role="tablist">
						   <li class="nav-item" role="presentation">
							<a href="auto-write.php" class="nav-link border-s-1">Auto Writer</a>
						  </li>
						  <li class="nav-item" role="presentation">
							<a href="scheduled.php" class="nav-link active">Scheduler</a>
						  </li>
						  <li class="nav-item" role="presentation">
							<a href="repurpose.php" class="nav-link">Repurpose</a>
						  </li>
						  <li class="nav-item" role="presentation">
							<a href="rss.php" class="nav-link">RSS</a>
						  </li>
						  <li class="nav-item" role="presentation">
							<a href="chatbot.php" class="nav-link">Chatbot</a>
						  </li>
						  <li class="nav-item" role="presentation">
							<a href="fine-tune-models.php" class="nav-link">Fine-tune Models</a>
						  </li>
						  <li class="nav-item" role="presentation">
							<a href="prompt.php" class="nav-link">AI Menu Prompts</a>
						  </li>
						  <li class="nav-item" role="presentation">
							<a href="setting.php" class="nav-link">Settings</a>
						  </li> 
						  <li class="nav-item" role="presentation">
							<a href="import.php" class="nav-link border-s-2" >Export/Import Settings</a>
						  </li>
						</ul>
						<div class="card h-auto">
							<div class="card-body p-0">
								<div class="table-responsive active-projects style-1">
								
									<table id="empoloyees-tblwrapper" class="table">
										<thead>
											<tr>
												<th>Description</th>
												<th>Keywords</th>
												<th>Status</th>
												<th>Interval</th>
												<th>Last generation</th>
												<th>Next generation</th>
												<th>Is running</th>
												<th>Run count</th>
												<th>Max run count</th>
												<th>Actions</th>
											</tr>
										</thead>
										<tbody>
											<tr>
												<td class="text-black">Write a rat story</td>
												<td>
													lion
												</td>
												<td><span class="badge badge-success badge-sm light">Active</span></td>
												<td>hourly</td>
												<td>4:50 am July 11, 2023</td>
												<td>5:50 am July 11, 2023</td>	
												<td>
													<span class="badge badge-light">No</span>
												</td>
												<td>1</td>
												<td>5</td>
												<td>
													<a href="javascript:void(0);" class="btn btn-primary light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M10.625 2.37519C10.7892 2.21104 10.984 2.08082 11.1985 1.99199C11.413 1.90315 11.6429 1.85742 11.875 1.85742C12.1071 1.85742 12.337 1.90315 12.5515 1.99199C12.766 2.08082 12.9608 2.21104 13.125 2.37519C13.2892 2.53934 13.4194 2.73422 13.5082 2.94869C13.597 3.16317 13.6428 3.39304 13.6428 3.62519C13.6428 3.85734 13.597 4.08721 13.5082 4.30168C13.4194 4.51616 13.2892 4.71104 13.125 4.87519L4.6875 13.3127L1.25 14.2502L2.1875 10.8127L10.625 2.37519Z" stroke="var(--primary)" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
													<a href="javascript:void(0);" class="btn btn-danger light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M1.875 4.25H3.125H13.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M11.875 4.25V13C11.875 13.3315 11.7433 13.6495 11.5089 13.8839C11.2745 14.1183 10.9565 14.25 10.625 14.25H4.375C4.04348 14.25 3.72554 14.1183 3.49112 13.8839C3.2567 13.6495 3.125 13.3315 3.125 13V4.25M5 4.25V3C5 2.66848 5.1317 2.35054 5.36612 2.11612C5.60054 1.8817 5.91848 1.75 6.25 1.75H8.75C9.08152 1.75 9.39946 1.8817 9.63388 2.11612C9.8683 2.35054 10 2.66848 10 3V4.25" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M6.25 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M8.75 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
												</td>
											</tr>
											<tr>
												<td class="text-black">Write a rat story</td>
												<td>
													lion
												</td>
												<td><span class="badge badge-success badge-sm light">Active</span></td>
												<td>hourly</td>
												<td>4:50 am July 11, 2023</td>
												<td>5:50 am July 11, 2023</td>	
												<td>
													<span class="badge badge-light">No</span>
												</td>
												<td>1</td>
												<td>5</td>
												<td>
													<a href="javascript:void(0);" class="btn btn-primary light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M10.625 2.37519C10.7892 2.21104 10.984 2.08082 11.1985 1.99199C11.413 1.90315 11.6429 1.85742 11.875 1.85742C12.1071 1.85742 12.337 1.90315 12.5515 1.99199C12.766 2.08082 12.9608 2.21104 13.125 2.37519C13.2892 2.53934 13.4194 2.73422 13.5082 2.94869C13.597 3.16317 13.6428 3.39304 13.6428 3.62519C13.6428 3.85734 13.597 4.08721 13.5082 4.30168C13.4194 4.51616 13.2892 4.71104 13.125 4.87519L4.6875 13.3127L1.25 14.2502L2.1875 10.8127L10.625 2.37519Z" stroke="var(--primary)" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
													<a href="javascript:void(0);" class="btn btn-danger light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M1.875 4.25H3.125H13.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M11.875 4.25V13C11.875 13.3315 11.7433 13.6495 11.5089 13.8839C11.2745 14.1183 10.9565 14.25 10.625 14.25H4.375C4.04348 14.25 3.72554 14.1183 3.49112 13.8839C3.2567 13.6495 3.125 13.3315 3.125 13V4.25M5 4.25V3C5 2.66848 5.1317 2.35054 5.36612 2.11612C5.60054 1.8817 5.91848 1.75 6.25 1.75H8.75C9.08152 1.75 9.39946 1.8817 9.63388 2.11612C9.8683 2.35054 10 2.66848 10 3V4.25" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M6.25 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M8.75 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
												</td>
											</tr>
											<tr>
												<td class="text-black">Write a rat story</td>
												<td>
													lion
												</td>
												<td><span class="badge badge-success badge-sm light">Active</span></td>
												<td>hourly</td>
												<td>4:50 am July 11, 2023</td>
												<td>5:50 am July 11, 2023</td>	
												<td>
													<span class="badge badge-light">No</span>
												</td>
												<td>1</td>
												<td>5</td>
												<td>
													<a href="javascript:void(0);" class="btn btn-primary light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M10.625 2.37519C10.7892 2.21104 10.984 2.08082 11.1985 1.99199C11.413 1.90315 11.6429 1.85742 11.875 1.85742C12.1071 1.85742 12.337 1.90315 12.5515 1.99199C12.766 2.08082 12.9608 2.21104 13.125 2.37519C13.2892 2.53934 13.4194 2.73422 13.5082 2.94869C13.597 3.16317 13.6428 3.39304 13.6428 3.62519C13.6428 3.85734 13.597 4.08721 13.5082 4.30168C13.4194 4.51616 13.2892 4.71104 13.125 4.87519L4.6875 13.3127L1.25 14.2502L2.1875 10.8127L10.625 2.37519Z" stroke="var(--primary)" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
													<a href="javascript:void(0);" class="btn btn-danger light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M1.875 4.25H3.125H13.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M11.875 4.25V13C11.875 13.3315 11.7433 13.6495 11.5089 13.8839C11.2745 14.1183 10.9565 14.25 10.625 14.25H4.375C4.04348 14.25 3.72554 14.1183 3.49112 13.8839C3.2567 13.6495 3.125 13.3315 3.125 13V4.25M5 4.25V3C5 2.66848 5.1317 2.35054 5.36612 2.11612C5.60054 1.8817 5.91848 1.75 6.25 1.75H8.75C9.08152 1.75 9.39946 1.8817 9.63388 2.11612C9.8683 2.35054 10 2.66848 10 3V4.25" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M6.25 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M8.75 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
												</td>
											</tr>
											<tr>
												<td class="text-black">Write a rat story</td>
												<td>
													lion
												</td>
												<td><span class="badge badge-success badge-sm light">Active</span></td>
												<td>hourly</td>
												<td>4:50 am July 11, 2023</td>
												<td>5:50 am July 11, 2023</td>	
												<td>
													<span class="badge badge-light">No</span>
												</td>
												<td>1</td>
												<td>5</td>
												<td>
													<a href="javascript:void(0);" class="btn btn-primary light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M10.625 2.37519C10.7892 2.21104 10.984 2.08082 11.1985 1.99199C11.413 1.90315 11.6429 1.85742 11.875 1.85742C12.1071 1.85742 12.337 1.90315 12.5515 1.99199C12.766 2.08082 12.9608 2.21104 13.125 2.37519C13.2892 2.53934 13.4194 2.73422 13.5082 2.94869C13.597 3.16317 13.6428 3.39304 13.6428 3.62519C13.6428 3.85734 13.597 4.08721 13.5082 4.30168C13.4194 4.51616 13.2892 4.71104 13.125 4.87519L4.6875 13.3127L1.25 14.2502L2.1875 10.8127L10.625 2.37519Z" stroke="var(--primary)" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
													<a href="javascript:void(0);" class="btn btn-danger light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M1.875 4.25H3.125H13.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M11.875 4.25V13C11.875 13.3315 11.7433 13.6495 11.5089 13.8839C11.2745 14.1183 10.9565 14.25 10.625 14.25H4.375C4.04348 14.25 3.72554 14.1183 3.49112 13.8839C3.2567 13.6495 3.125 13.3315 3.125 13V4.25M5 4.25V3C5 2.66848 5.1317 2.35054 5.36612 2.11612C5.60054 1.8817 5.91848 1.75 6.25 1.75H8.75C9.08152 1.75 9.39946 1.8817 9.63388 2.11612C9.8683 2.35054 10 2.66848 10 3V4.25" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M6.25 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M8.75 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
												</td>
											</tr>
											<tr>
												<td class="text-black">Write a rat story</td>
												<td>
													lion
												</td>
												<td><span class="badge badge-success badge-sm light">Active</span></td>
												<td>hourly</td>
												<td>4:50 am July 11, 2023</td>
												<td>5:50 am July 11, 2023</td>	
												<td>
													<span class="badge badge-light">No</span>
												</td>
												<td>1</td>
												<td>5</td>
												<td>
													<a href="javascript:void(0);" class="btn btn-primary light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M10.625 2.37519C10.7892 2.21104 10.984 2.08082 11.1985 1.99199C11.413 1.90315 11.6429 1.85742 11.875 1.85742C12.1071 1.85742 12.337 1.90315 12.5515 1.99199C12.766 2.08082 12.9608 2.21104 13.125 2.37519C13.2892 2.53934 13.4194 2.73422 13.5082 2.94869C13.597 3.16317 13.6428 3.39304 13.6428 3.62519C13.6428 3.85734 13.597 4.08721 13.5082 4.30168C13.4194 4.51616 13.2892 4.71104 13.125 4.87519L4.6875 13.3127L1.25 14.2502L2.1875 10.8127L10.625 2.37519Z" stroke="var(--primary)" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
													<a href="javascript:void(0);" class="btn btn-danger light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M1.875 4.25H3.125H13.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M11.875 4.25V13C11.875 13.3315 11.7433 13.6495 11.5089 13.8839C11.2745 14.1183 10.9565 14.25 10.625 14.25H4.375C4.04348 14.25 3.72554 14.1183 3.49112 13.8839C3.2567 13.6495 3.125 13.3315 3.125 13V4.25M5 4.25V3C5 2.66848 5.1317 2.35054 5.36612 2.11612C5.60054 1.8817 5.91848 1.75 6.25 1.75H8.75C9.08152 1.75 9.39946 1.8817 9.63388 2.11612C9.8683 2.35054 10 2.66848 10 3V4.25" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M6.25 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M8.75 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
												</td>
											</tr>
											<tr>
												<td class="text-black">Write a rat story</td>
												<td>
													lion
												</td>
												<td><span class="badge badge-success badge-sm light">Active</span></td>
												<td>hourly</td>
												<td>4:50 am July 11, 2023</td>
												<td>5:50 am July 11, 2023</td>	
												<td>
													<span class="badge badge-success">Yes</span>
												</td>
												<td>1</td>
												<td>5</td>
												<td>
													<a href="javascript:void(0);" class="btn btn-primary light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M10.625 2.37519C10.7892 2.21104 10.984 2.08082 11.1985 1.99199C11.413 1.90315 11.6429 1.85742 11.875 1.85742C12.1071 1.85742 12.337 1.90315 12.5515 1.99199C12.766 2.08082 12.9608 2.21104 13.125 2.37519C13.2892 2.53934 13.4194 2.73422 13.5082 2.94869C13.597 3.16317 13.6428 3.39304 13.6428 3.62519C13.6428 3.85734 13.597 4.08721 13.5082 4.30168C13.4194 4.51616 13.2892 4.71104 13.125 4.87519L4.6875 13.3127L1.25 14.2502L2.1875 10.8127L10.625 2.37519Z" stroke="var(--primary)" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
													<a href="javascript:void(0);" class="btn btn-danger light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M1.875 4.25H3.125H13.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M11.875 4.25V13C11.875 13.3315 11.7433 13.6495 11.5089 13.8839C11.2745 14.1183 10.9565 14.25 10.625 14.25H4.375C4.04348 14.25 3.72554 14.1183 3.49112 13.8839C3.2567 13.6495 3.125 13.3315 3.125 13V4.25M5 4.25V3C5 2.66848 5.1317 2.35054 5.36612 2.11612C5.60054 1.8817 5.91848 1.75 6.25 1.75H8.75C9.08152 1.75 9.39946 1.8817 9.63388 2.11612C9.8683 2.35054 10 2.66848 10 3V4.25" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M6.25 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M8.75 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
												</td>
											</tr>
											<tr>
												<td class="text-black">Write a rat story</td>
												<td>
													lion
												</td>
												<td><span class="badge badge-success badge-sm light">Active</span></td>
												<td>hourly</td>
												<td>4:50 am July 11, 2023</td>
												<td>5:50 am July 11, 2023</td>	
												<td>
													<span class="badge badge-light">No</span>
												</td>
												<td>1</td>
												<td>5</td>
												<td>
													<a href="javascript:void(0);" class="btn btn-primary light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M10.625 2.37519C10.7892 2.21104 10.984 2.08082 11.1985 1.99199C11.413 1.90315 11.6429 1.85742 11.875 1.85742C12.1071 1.85742 12.337 1.90315 12.5515 1.99199C12.766 2.08082 12.9608 2.21104 13.125 2.37519C13.2892 2.53934 13.4194 2.73422 13.5082 2.94869C13.597 3.16317 13.6428 3.39304 13.6428 3.62519C13.6428 3.85734 13.597 4.08721 13.5082 4.30168C13.4194 4.51616 13.2892 4.71104 13.125 4.87519L4.6875 13.3127L1.25 14.2502L2.1875 10.8127L10.625 2.37519Z" stroke="var(--primary)" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
													<a href="javascript:void(0);" class="btn btn-danger light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M1.875 4.25H3.125H13.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M11.875 4.25V13C11.875 13.3315 11.7433 13.6495 11.5089 13.8839C11.2745 14.1183 10.9565 14.25 10.625 14.25H4.375C4.04348 14.25 3.72554 14.1183 3.49112 13.8839C3.2567 13.6495 3.125 13.3315 3.125 13V4.25M5 4.25V3C5 2.66848 5.1317 2.35054 5.36612 2.11612C5.60054 1.8817 5.91848 1.75 6.25 1.75H8.75C9.08152 1.75 9.39946 1.8817 9.63388 2.11612C9.8683 2.35054 10 2.66848 10 3V4.25" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M6.25 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M8.75 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
												</td>
											</tr>
											<tr>
												<td class="text-black">Write a rat story</td>
												<td>
													lion
												</td>
												<td><span class="badge badge-success badge-sm light">Active</span></td>
												<td>hourly</td>
												<td>4:50 am July 11, 2023</td>
												<td>5:50 am July 11, 2023</td>	
												<td>
													<span class="badge badge-light">No</span>
												</td>
												<td>1</td>
												<td>5</td>
												<td>
													<a href="javascript:void(0);" class="btn btn-primary light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M10.625 2.37519C10.7892 2.21104 10.984 2.08082 11.1985 1.99199C11.413 1.90315 11.6429 1.85742 11.875 1.85742C12.1071 1.85742 12.337 1.90315 12.5515 1.99199C12.766 2.08082 12.9608 2.21104 13.125 2.37519C13.2892 2.53934 13.4194 2.73422 13.5082 2.94869C13.597 3.16317 13.6428 3.39304 13.6428 3.62519C13.6428 3.85734 13.597 4.08721 13.5082 4.30168C13.4194 4.51616 13.2892 4.71104 13.125 4.87519L4.6875 13.3127L1.25 14.2502L2.1875 10.8127L10.625 2.37519Z" stroke="var(--primary)" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
													<a href="javascript:void(0);" class="btn btn-danger light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M1.875 4.25H3.125H13.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M11.875 4.25V13C11.875 13.3315 11.7433 13.6495 11.5089 13.8839C11.2745 14.1183 10.9565 14.25 10.625 14.25H4.375C4.04348 14.25 3.72554 14.1183 3.49112 13.8839C3.2567 13.6495 3.125 13.3315 3.125 13V4.25M5 4.25V3C5 2.66848 5.1317 2.35054 5.36612 2.11612C5.60054 1.8817 5.91848 1.75 6.25 1.75H8.75C9.08152 1.75 9.39946 1.8817 9.63388 2.11612C9.8683 2.35054 10 2.66848 10 3V4.25" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M6.25 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M8.75 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
												</td>
											</tr>
											<tr>
												<td class="text-black">Write a rat story</td>
												<td>
													lion
												</td>
												<td><span class="badge badge-success badge-sm light">Active</span></td>
												<td>hourly</td>
												<td>4:50 am July 11, 2023</td>
												<td>5:50 am July 11, 2023</td>	
												<td>
													<span class="badge badge-light">No</span>
												</td>
												<td>1</td>
												<td>5</td>
												<td>
													<a href="javascript:void(0);" class="btn btn-primary light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M10.625 2.37519C10.7892 2.21104 10.984 2.08082 11.1985 1.99199C11.413 1.90315 11.6429 1.85742 11.875 1.85742C12.1071 1.85742 12.337 1.90315 12.5515 1.99199C12.766 2.08082 12.9608 2.21104 13.125 2.37519C13.2892 2.53934 13.4194 2.73422 13.5082 2.94869C13.597 3.16317 13.6428 3.39304 13.6428 3.62519C13.6428 3.85734 13.597 4.08721 13.5082 4.30168C13.4194 4.51616 13.2892 4.71104 13.125 4.87519L4.6875 13.3127L1.25 14.2502L2.1875 10.8127L10.625 2.37519Z" stroke="var(--primary)" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
													<a href="javascript:void(0);" class="btn btn-danger light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M1.875 4.25H3.125H13.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M11.875 4.25V13C11.875 13.3315 11.7433 13.6495 11.5089 13.8839C11.2745 14.1183 10.9565 14.25 10.625 14.25H4.375C4.04348 14.25 3.72554 14.1183 3.49112 13.8839C3.2567 13.6495 3.125 13.3315 3.125 13V4.25M5 4.25V3C5 2.66848 5.1317 2.35054 5.36612 2.11612C5.60054 1.8817 5.91848 1.75 6.25 1.75H8.75C9.08152 1.75 9.39946 1.8817 9.63388 2.11612C9.8683 2.35054 10 2.66848 10 3V4.25" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M6.25 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M8.75 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
												</td>
											</tr>
											<tr>
												<td class="text-black">Write a rat story</td>
												<td>
													lion
												</td>
												<td><span class="badge badge-success badge-sm light">Active</span></td>
												<td>hourly</td>
												<td>4:50 am July 11, 2023</td>
												<td>5:50 am July 11, 2023</td>	
												<td>
													<span class="badge badge-success">Yes</span>
												</td>
												<td>1</td>
												<td>5</td>
												<td>
													<a href="javascript:void(0);" class="btn btn-primary light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M10.625 2.37519C10.7892 2.21104 10.984 2.08082 11.1985 1.99199C11.413 1.90315 11.6429 1.85742 11.875 1.85742C12.1071 1.85742 12.337 1.90315 12.5515 1.99199C12.766 2.08082 12.9608 2.21104 13.125 2.37519C13.2892 2.53934 13.4194 2.73422 13.5082 2.94869C13.597 3.16317 13.6428 3.39304 13.6428 3.62519C13.6428 3.85734 13.597 4.08721 13.5082 4.30168C13.4194 4.51616 13.2892 4.71104 13.125 4.87519L4.6875 13.3127L1.25 14.2502L2.1875 10.8127L10.625 2.37519Z" stroke="var(--primary)" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
													<a href="javascript:void(0);" class="btn btn-danger light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M1.875 4.25H3.125H13.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M11.875 4.25V13C11.875 13.3315 11.7433 13.6495 11.5089 13.8839C11.2745 14.1183 10.9565 14.25 10.625 14.25H4.375C4.04348 14.25 3.72554 14.1183 3.49112 13.8839C3.2567 13.6495 3.125 13.3315 3.125 13V4.25M5 4.25V3C5 2.66848 5.1317 2.35054 5.36612 2.11612C5.60054 1.8817 5.91848 1.75 6.25 1.75H8.75C9.08152 1.75 9.39946 1.8817 9.63388 2.11612C9.8683 2.35054 10 2.66848 10 3V4.25" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M6.25 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M8.75 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
												</td>
											</tr><tr>
												<td class="text-black">Write a rat story</td>
												<td>
													lion
												</td>
												<td><span class="badge badge-success badge-sm light">Active</span></td>
												<td>hourly</td>
												<td>4:50 am July 11, 2023</td>
												<td>5:50 am July 11, 2023</td>	
												<td>
													<span class="badge badge-light">No</span>
												</td>
												<td>1</td>
												<td>5</td>
												<td>
													<a href="javascript:void(0);" class="btn btn-primary light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M10.625 2.37519C10.7892 2.21104 10.984 2.08082 11.1985 1.99199C11.413 1.90315 11.6429 1.85742 11.875 1.85742C12.1071 1.85742 12.337 1.90315 12.5515 1.99199C12.766 2.08082 12.9608 2.21104 13.125 2.37519C13.2892 2.53934 13.4194 2.73422 13.5082 2.94869C13.597 3.16317 13.6428 3.39304 13.6428 3.62519C13.6428 3.85734 13.597 4.08721 13.5082 4.30168C13.4194 4.51616 13.2892 4.71104 13.125 4.87519L4.6875 13.3127L1.25 14.2502L2.1875 10.8127L10.625 2.37519Z" stroke="var(--primary)" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
													<a href="javascript:void(0);" class="btn btn-danger light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M1.875 4.25H3.125H13.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M11.875 4.25V13C11.875 13.3315 11.7433 13.6495 11.5089 13.8839C11.2745 14.1183 10.9565 14.25 10.625 14.25H4.375C4.04348 14.25 3.72554 14.1183 3.49112 13.8839C3.2567 13.6495 3.125 13.3315 3.125 13V4.25M5 4.25V3C5 2.66848 5.1317 2.35054 5.36612 2.11612C5.60054 1.8817 5.91848 1.75 6.25 1.75H8.75C9.08152 1.75 9.39946 1.8817 9.63388 2.11612C9.8683 2.35054 10 2.66848 10 3V4.25" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M6.25 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M8.75 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
												</td>
											</tr><tr>
												<td class="text-black">Write a rat story</td>
												<td>
													lion
												</td>
												<td><span class="badge badge-success badge-sm light">Active</span></td>
												<td>hourly</td>
												<td>4:50 am July 11, 2023</td>
												<td>5:50 am July 11, 2023</td>	
												<td>
													<span class="badge badge-light">No</span>
												</td>
												<td>1</td>
												<td>5</td>
												<td>
													<a href="javascript:void(0);" class="btn btn-primary light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M10.625 2.37519C10.7892 2.21104 10.984 2.08082 11.1985 1.99199C11.413 1.90315 11.6429 1.85742 11.875 1.85742C12.1071 1.85742 12.337 1.90315 12.5515 1.99199C12.766 2.08082 12.9608 2.21104 13.125 2.37519C13.2892 2.53934 13.4194 2.73422 13.5082 2.94869C13.597 3.16317 13.6428 3.39304 13.6428 3.62519C13.6428 3.85734 13.597 4.08721 13.5082 4.30168C13.4194 4.51616 13.2892 4.71104 13.125 4.87519L4.6875 13.3127L1.25 14.2502L2.1875 10.8127L10.625 2.37519Z" stroke="var(--primary)" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
													<a href="javascript:void(0);" class="btn btn-danger light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M1.875 4.25H3.125H13.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M11.875 4.25V13C11.875 13.3315 11.7433 13.6495 11.5089 13.8839C11.2745 14.1183 10.9565 14.25 10.625 14.25H4.375C4.04348 14.25 3.72554 14.1183 3.49112 13.8839C3.2567 13.6495 3.125 13.3315 3.125 13V4.25M5 4.25V3C5 2.66848 5.1317 2.35054 5.36612 2.11612C5.60054 1.8817 5.91848 1.75 6.25 1.75H8.75C9.08152 1.75 9.39946 1.8817 9.63388 2.11612C9.8683 2.35054 10 2.66848 10 3V4.25" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M6.25 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M8.75 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
												</td>
											</tr><tr>
												<td class="text-black">Write a rat story</td>
												<td>
													lion
												</td>
												<td><span class="badge badge-success badge-sm light">Active</span></td>
												<td>hourly</td>
												<td>4:50 am July 11, 2023</td>
												<td>5:50 am July 11, 2023</td>	
												<td>
													<span class="badge badge-light">No</span>
												</td>
												<td>1</td>
												<td>5</td>
												<td>
													<a href="javascript:void(0);" class="btn btn-primary light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M10.625 2.37519C10.7892 2.21104 10.984 2.08082 11.1985 1.99199C11.413 1.90315 11.6429 1.85742 11.875 1.85742C12.1071 1.85742 12.337 1.90315 12.5515 1.99199C12.766 2.08082 12.9608 2.21104 13.125 2.37519C13.2892 2.53934 13.4194 2.73422 13.5082 2.94869C13.597 3.16317 13.6428 3.39304 13.6428 3.62519C13.6428 3.85734 13.597 4.08721 13.5082 4.30168C13.4194 4.51616 13.2892 4.71104 13.125 4.87519L4.6875 13.3127L1.25 14.2502L2.1875 10.8127L10.625 2.37519Z" stroke="var(--primary)" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
													<a href="javascript:void(0);" class="btn btn-danger light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M1.875 4.25H3.125H13.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M11.875 4.25V13C11.875 13.3315 11.7433 13.6495 11.5089 13.8839C11.2745 14.1183 10.9565 14.25 10.625 14.25H4.375C4.04348 14.25 3.72554 14.1183 3.49112 13.8839C3.2567 13.6495 3.125 13.3315 3.125 13V4.25M5 4.25V3C5 2.66848 5.1317 2.35054 5.36612 2.11612C5.60054 1.8817 5.91848 1.75 6.25 1.75H8.75C9.08152 1.75 9.39946 1.8817 9.63388 2.11612C9.8683 2.35054 10 2.66848 10 3V4.25" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M6.25 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M8.75 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
													
												</td>
											</tr><tr>
												<td class="text-black">Write a rat story</td>
												<td>
													lion
												</td>
												<td><span class="badge badge-success badge-sm light">Active</span></td>
												<td>hourly</td>
												<td>4:50 am July 11, 2023</td>
												<td>5:50 am July 11, 2023</td>	
												<td>
													<span class="badge badge-light">No</span>
												</td>
												<td>1</td>
												<td>5</td>
												<td>
													<a href="javascript:void(0);" class="btn btn-primary light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M10.625 2.37519C10.7892 2.21104 10.984 2.08082 11.1985 1.99199C11.413 1.90315 11.6429 1.85742 11.875 1.85742C12.1071 1.85742 12.337 1.90315 12.5515 1.99199C12.766 2.08082 12.9608 2.21104 13.125 2.37519C13.2892 2.53934 13.4194 2.73422 13.5082 2.94869C13.597 3.16317 13.6428 3.39304 13.6428 3.62519C13.6428 3.85734 13.597 4.08721 13.5082 4.30168C13.4194 4.51616 13.2892 4.71104 13.125 4.87519L4.6875 13.3127L1.25 14.2502L2.1875 10.8127L10.625 2.37519Z" stroke="var(--primary)" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
													<a href="javascript:void(0);" class="btn btn-danger light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M1.875 4.25H3.125H13.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M11.875 4.25V13C11.875 13.3315 11.7433 13.6495 11.5089 13.8839C11.2745 14.1183 10.9565 14.25 10.625 14.25H4.375C4.04348 14.25 3.72554 14.1183 3.49112 13.8839C3.2567 13.6495 3.125 13.3315 3.125 13V4.25M5 4.25V3C5 2.66848 5.1317 2.35054 5.36612 2.11612C5.60054 1.8817 5.91848 1.75 6.25 1.75H8.75C9.08152 1.75 9.39946 1.8817 9.63388 2.11612C9.8683 2.35054 10 2.66848 10 3V4.25" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M6.25 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M8.75 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
													
												</td>
											</tr><tr>
												<td class="text-black">Write a rat story</td>
												<td>
													lion
												</td>
												<td><span class="badge badge-success badge-sm light">Active</span></td>
												<td>hourly</td>
												<td>4:50 am July 11, 2023</td>
												<td>5:50 am July 11, 2023</td>	
												<td>
													<span class="badge badge-success">Yes</span>
												</td>
												<td>1</td>
												<td>5</td>
												<td>
													<a href="javascript:void(0);" class="btn btn-primary light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M10.625 2.37519C10.7892 2.21104 10.984 2.08082 11.1985 1.99199C11.413 1.90315 11.6429 1.85742 11.875 1.85742C12.1071 1.85742 12.337 1.90315 12.5515 1.99199C12.766 2.08082 12.9608 2.21104 13.125 2.37519C13.2892 2.53934 13.4194 2.73422 13.5082 2.94869C13.597 3.16317 13.6428 3.39304 13.6428 3.62519C13.6428 3.85734 13.597 4.08721 13.5082 4.30168C13.4194 4.51616 13.2892 4.71104 13.125 4.87519L4.6875 13.3127L1.25 14.2502L2.1875 10.8127L10.625 2.37519Z" stroke="var(--primary)" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
													<a href="javascript:void(0);" class="btn btn-danger light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M1.875 4.25H3.125H13.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M11.875 4.25V13C11.875 13.3315 11.7433 13.6495 11.5089 13.8839C11.2745 14.1183 10.9565 14.25 10.625 14.25H4.375C4.04348 14.25 3.72554 14.1183 3.49112 13.8839C3.2567 13.6495 3.125 13.3315 3.125 13V4.25M5 4.25V3C5 2.66848 5.1317 2.35054 5.36612 2.11612C5.60054 1.8817 5.91848 1.75 6.25 1.75H8.75C9.08152 1.75 9.39946 1.8817 9.63388 2.11612C9.8683 2.35054 10 2.66848 10 3V4.25" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M6.25 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M8.75 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
													
												</td>
											</tr><tr>
												<td class="text-black">Write a rat story</td>
												<td>
													lion
												</td>
												<td><span class="badge badge-success badge-sm light">Active</span></td>
												<td>hourly</td>
												<td>4:50 am July 11, 2023</td>
												<td>5:50 am July 11, 2023</td>	
												<td>
													<span class="badge badge-light">No</span>
												</td>
												<td>1</td>
												<td>5</td>
												<td>
													<a href="javascript:void(0);" class="btn btn-primary light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M10.625 2.37519C10.7892 2.21104 10.984 2.08082 11.1985 1.99199C11.413 1.90315 11.6429 1.85742 11.875 1.85742C12.1071 1.85742 12.337 1.90315 12.5515 1.99199C12.766 2.08082 12.9608 2.21104 13.125 2.37519C13.2892 2.53934 13.4194 2.73422 13.5082 2.94869C13.597 3.16317 13.6428 3.39304 13.6428 3.62519C13.6428 3.85734 13.597 4.08721 13.5082 4.30168C13.4194 4.51616 13.2892 4.71104 13.125 4.87519L4.6875 13.3127L1.25 14.2502L2.1875 10.8127L10.625 2.37519Z" stroke="var(--primary)" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
													<a href="javascript:void(0);" class="btn btn-danger light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M1.875 4.25H3.125H13.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M11.875 4.25V13C11.875 13.3315 11.7433 13.6495 11.5089 13.8839C11.2745 14.1183 10.9565 14.25 10.625 14.25H4.375C4.04348 14.25 3.72554 14.1183 3.49112 13.8839C3.2567 13.6495 3.125 13.3315 3.125 13V4.25M5 4.25V3C5 2.66848 5.1317 2.35054 5.36612 2.11612C5.60054 1.8817 5.91848 1.75 6.25 1.75H8.75C9.08152 1.75 9.39946 1.8817 9.63388 2.11612C9.8683 2.35054 10 2.66848 10 3V4.25" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M6.25 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M8.75 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
													
												</td>
											</tr><tr>
												<td class="text-black">Write a rat story</td>
												<td>
													lion
												</td>
												<td><span class="badge badge-success badge-sm light">Active</span></td>
												<td>hourly</td>
												<td>4:50 am July 11, 2023</td>
												<td>5:50 am July 11, 2023</td>	
												<td>
													<span class="badge badge-light">No</span>
												</td>
												<td>1</td>
												<td>5</td>
												<td>
													<a href="javascript:void(0);" class="btn btn-primary light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M10.625 2.37519C10.7892 2.21104 10.984 2.08082 11.1985 1.99199C11.413 1.90315 11.6429 1.85742 11.875 1.85742C12.1071 1.85742 12.337 1.90315 12.5515 1.99199C12.766 2.08082 12.9608 2.21104 13.125 2.37519C13.2892 2.53934 13.4194 2.73422 13.5082 2.94869C13.597 3.16317 13.6428 3.39304 13.6428 3.62519C13.6428 3.85734 13.597 4.08721 13.5082 4.30168C13.4194 4.51616 13.2892 4.71104 13.125 4.87519L4.6875 13.3127L1.25 14.2502L2.1875 10.8127L10.625 2.37519Z" stroke="var(--primary)" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
													<a href="javascript:void(0);" class="btn btn-danger light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M1.875 4.25H3.125H13.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M11.875 4.25V13C11.875 13.3315 11.7433 13.6495 11.5089 13.8839C11.2745 14.1183 10.9565 14.25 10.625 14.25H4.375C4.04348 14.25 3.72554 14.1183 3.49112 13.8839C3.2567 13.6495 3.125 13.3315 3.125 13V4.25M5 4.25V3C5 2.66848 5.1317 2.35054 5.36612 2.11612C5.60054 1.8817 5.91848 1.75 6.25 1.75H8.75C9.08152 1.75 9.39946 1.8817 9.63388 2.11612C9.8683 2.35054 10 2.66848 10 3V4.25" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M6.25 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M8.75 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
													
												</td>
											</tr><tr>
												<td class="text-black">Write a rat story</td>
												<td>
													lion
												</td>
												<td><span class="badge badge-success badge-sm light">Active</span></td>
												<td>hourly</td>
												<td>4:50 am July 11, 2023</td>
												<td>5:50 am July 11, 2023</td>	
												<td>
													<span class="badge badge-light">No</span>
												</td>
												<td>1</td>
												<td>5</td>
												<td>
													<a href="javascript:void(0);" class="btn btn-primary light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M10.625 2.37519C10.7892 2.21104 10.984 2.08082 11.1985 1.99199C11.413 1.90315 11.6429 1.85742 11.875 1.85742C12.1071 1.85742 12.337 1.90315 12.5515 1.99199C12.766 2.08082 12.9608 2.21104 13.125 2.37519C13.2892 2.53934 13.4194 2.73422 13.5082 2.94869C13.597 3.16317 13.6428 3.39304 13.6428 3.62519C13.6428 3.85734 13.597 4.08721 13.5082 4.30168C13.4194 4.51616 13.2892 4.71104 13.125 4.87519L4.6875 13.3127L1.25 14.2502L2.1875 10.8127L10.625 2.37519Z" stroke="var(--primary)" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
													<a href="javascript:void(0);" class="btn btn-danger light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M1.875 4.25H3.125H13.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M11.875 4.25V13C11.875 13.3315 11.7433 13.6495 11.5089 13.8839C11.2745 14.1183 10.9565 14.25 10.625 14.25H4.375C4.04348 14.25 3.72554 14.1183 3.49112 13.8839C3.2567 13.6495 3.125 13.3315 3.125 13V4.25M5 4.25V3C5 2.66848 5.1317 2.35054 5.36612 2.11612C5.60054 1.8817 5.91848 1.75 6.25 1.75H8.75C9.08152 1.75 9.39946 1.8817 9.63388 2.11612C9.8683 2.35054 10 2.66848 10 3V4.25" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M6.25 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M8.75 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
													
												</td>
											</tr><tr>
												<td class="text-black">Write a rat story</td>
												<td>
													lion
												</td>
												<td><span class="badge badge-success badge-sm light">Active</span></td>
												<td>hourly</td>
												<td>4:50 am July 11, 2023</td>
												<td>5:50 am July 11, 2023</td>	
												<td>
													<span class="badge badge-light">No</span>
												</td>
												<td>1</td>
												<td>5</td>
												<td>
													<a href="javascript:void(0);" class="btn btn-primary light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M10.625 2.37519C10.7892 2.21104 10.984 2.08082 11.1985 1.99199C11.413 1.90315 11.6429 1.85742 11.875 1.85742C12.1071 1.85742 12.337 1.90315 12.5515 1.99199C12.766 2.08082 12.9608 2.21104 13.125 2.37519C13.2892 2.53934 13.4194 2.73422 13.5082 2.94869C13.597 3.16317 13.6428 3.39304 13.6428 3.62519C13.6428 3.85734 13.597 4.08721 13.5082 4.30168C13.4194 4.51616 13.2892 4.71104 13.125 4.87519L4.6875 13.3127L1.25 14.2502L2.1875 10.8127L10.625 2.37519Z" stroke="var(--primary)" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
													<a href="javascript:void(0);" class="btn btn-danger light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M1.875 4.25H3.125H13.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M11.875 4.25V13C11.875 13.3315 11.7433 13.6495 11.5089 13.8839C11.2745 14.1183 10.9565 14.25 10.625 14.25H4.375C4.04348 14.25 3.72554 14.1183 3.49112 13.8839C3.2567 13.6495 3.125 13.3315 3.125 13V4.25M5 4.25V3C5 2.66848 5.1317 2.35054 5.36612 2.11612C5.60054 1.8817 5.91848 1.75 6.25 1.75H8.75C9.08152 1.75 9.39946 1.8817 9.63388 2.11612C9.8683 2.35054 10 2.66848 10 3V4.25" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M6.25 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M8.75 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
													
												</td>
											</tr><tr>
												<td class="text-black">Write a rat story</td>
												<td>
													lion
												</td>
												<td><span class="badge badge-success badge-sm light">Active</span></td>
												<td>hourly</td>
												<td>4:50 am July 11, 2023</td>
												<td>5:50 am July 11, 2023</td>	
												<td>
													<span class="badge badge-light">No</span>
												</td>
												<td>1</td>
												<td>5</td>
												<td>
													<a href="javascript:void(0);" class="btn btn-primary light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M10.625 2.37519C10.7892 2.21104 10.984 2.08082 11.1985 1.99199C11.413 1.90315 11.6429 1.85742 11.875 1.85742C12.1071 1.85742 12.337 1.90315 12.5515 1.99199C12.766 2.08082 12.9608 2.21104 13.125 2.37519C13.2892 2.53934 13.4194 2.73422 13.5082 2.94869C13.597 3.16317 13.6428 3.39304 13.6428 3.62519C13.6428 3.85734 13.597 4.08721 13.5082 4.30168C13.4194 4.51616 13.2892 4.71104 13.125 4.87519L4.6875 13.3127L1.25 14.2502L2.1875 10.8127L10.625 2.37519Z" stroke="var(--primary)" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
													<a href="javascript:void(0);" class="btn btn-danger light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M1.875 4.25H3.125H13.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M11.875 4.25V13C11.875 13.3315 11.7433 13.6495 11.5089 13.8839C11.2745 14.1183 10.9565 14.25 10.625 14.25H4.375C4.04348 14.25 3.72554 14.1183 3.49112 13.8839C3.2567 13.6495 3.125 13.3315 3.125 13V4.25M5 4.25V3C5 2.66848 5.1317 2.35054 5.36612 2.11612C5.60054 1.8817 5.91848 1.75 6.25 1.75H8.75C9.08152 1.75 9.39946 1.8817 9.63388 2.11612C9.8683 2.35054 10 2.66848 10 3V4.25" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M6.25 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M8.75 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
													
												</td>
											</tr><tr>
												<td class="text-black">Write a rat story</td>
												<td>
													lion
												</td>
												<td><span class="badge badge-success badge-sm light">Active</span></td>
												<td>hourly</td>
												<td>4:50 am July 11, 2023</td>
												<td>5:50 am July 11, 2023</td>	
												<td>
													<span class="badge badge-light">No</span>
												</td>
												<td>1</td>
												<td>5</td>
												<td>
													<a href="javascript:void(0);" class="btn btn-primary light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M10.625 2.37519C10.7892 2.21104 10.984 2.08082 11.1985 1.99199C11.413 1.90315 11.6429 1.85742 11.875 1.85742C12.1071 1.85742 12.337 1.90315 12.5515 1.99199C12.766 2.08082 12.9608 2.21104 13.125 2.37519C13.2892 2.53934 13.4194 2.73422 13.5082 2.94869C13.597 3.16317 13.6428 3.39304 13.6428 3.62519C13.6428 3.85734 13.597 4.08721 13.5082 4.30168C13.4194 4.51616 13.2892 4.71104 13.125 4.87519L4.6875 13.3127L1.25 14.2502L2.1875 10.8127L10.625 2.37519Z" stroke="var(--primary)" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
													<a href="javascript:void(0);" class="btn btn-danger light btn-sharp">
														<svg width="15" height="16" viewBox="0 0 15 16" fill="none" xmlns="http://www.w3.org/2000/svg">
														<path d="M1.875 4.25H3.125H13.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M11.875 4.25V13C11.875 13.3315 11.7433 13.6495 11.5089 13.8839C11.2745 14.1183 10.9565 14.25 10.625 14.25H4.375C4.04348 14.25 3.72554 14.1183 3.49112 13.8839C3.2567 13.6495 3.125 13.3315 3.125 13V4.25M5 4.25V3C5 2.66848 5.1317 2.35054 5.36612 2.11612C5.60054 1.8817 5.91848 1.75 6.25 1.75H8.75C9.08152 1.75 9.39946 1.8817 9.63388 2.11612C9.8683 2.35054 10 2.66848 10 3V4.25" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M6.25 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														<path d="M8.75 7.375V11.125" stroke="#FF5B5B" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
														</svg>
													</a>
													
												</td>
											</tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
        </div>
		
		
		
        <!--**********************************
            Content body end
        ***********************************-->
		<!-- Button trigger modal -->
			
			
			
		
		
        <!--**********************************
            Footer start
        ***********************************-->
        <?php include 'elements/footer.php'; ?>
        <!--**********************************
            Footer end
			
			
        ***********************************-->

		<!--**********************************
           Support ticket button start
        ***********************************-->

        <!--**********************************
           Support ticket button end
        ***********************************-->
			


	</div>
    <!--**********************************
        Main wrapper end
    ***********************************-->

    <!--**********************************
        Scripts
    ***********************************-->
	
    <!-- Required vendors -->
  <?php include 'elements/page-js.php'; ?>
    
	
	
</body>
</html>